### ISSUE TITLE
config_flow not working

### ISSUE THREAD

**Issue by walterb65** [gazoodle/gecko-home-assistant#1]
Hello,

I have tried to install your homeassistant integration, but I'm not able run the configuration.
I have installed geckolib 0.3.15 first and then created the gecko custom integration as described.
In Integration Gecko show up but when selecting it terminate.

Logger: aiohttp.server
Source: custom_components/gecko/config_flow.py:32
First occurred: 21:12:19 (1 occurrences)
Last logged: 21:12:19

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 552, in async_create_flow
    flow = cast(ConfigFlow, handler())
  File "/config/custom_components/gecko/config_flow.py", line 32, in __init__
    self._locator.start_discovery()
AttributeError: 'GeckoLocator' object has no attribute 'start_discovery'

best regards
Walter

**Comment by gazoodle** [comment]
It looks like it doesn’t have the latest geckolib installed correctly which is odd because you say you installed the latest version. 

The HA integration should have pulled the latest one in, but I think that only happens if it is installed from HACS. 

I’ll take a look in a clean install and see what happens.

**Comment by walterb65** [comment]
Can I install from HACS? I've searched for it in HACS but it doesn't show up in HACS integrations.

**Comment by gazoodle** [comment]
If you add this repo as a HACS custom repo, that should work. This should help https://hacs.xyz/docs/faq/custom_repositories

I’m in the process of getting it added to the HACS list but it will take a while.

**Comment by walterb65** [comment]
Installing via HACS has the same issue.
I did the following steps:
1. Uninstalled geckolib library
2. Deleted gecko folder in custom_components
3. Restart HA
4. Added your repo to HACS an install
5. Restart HA
6. Try to add component via integrations
Stacktrace show the same error.
I'm running HA on a raspberry 4 using HA Core 2020.12.0 so HA is running in a Docker container

**Comment by walterb65** [comment]
geckolib was not installed automatically, even not with HACS. When installing manually it is located inside the container at /usr/local/lib/python3.8/site-packages.

**Comment by gazoodle** [comment]
Can you try again please?

**Comment by walterb65** [comment]
Sorry same issue. I removed everything including geckolib restart HA and reinstalled from HACS. After reboot tried to add integration again but still the same error in log. I've checked geckolib in the docker container and it was added automatically. It look like the integration cannot access/find the installed lob.

**Comment by walterb65** [comment]
Got it working, there was an old version 0.3.11 of the lib in /config/deps/lib/python3.8/site-packages/geckolib

Thanks for your help.
