### ISSUE TITLE
Handling/Recovery when Gecko units are disconnected (RF Error, tub powered off for maintanence)

### ISSUE THREAD

**Issue by rct** [gazoodle/gecko-home-assistant#21]
## Version of the custom_component
Version 0.0.5 - from manifest.json
Version 0.0.1 - from const.py

With local modification to line 45 of __iniy__.py from issue # 

Original
```
            facade = await locator.get_spa_from_identifier(spa_identifier).get_facade(False)
```

Changed to
```
            spa = await hass.async_add_executor_job(locator.get_spa_from_identifier, spa_identifier)
            facade = await hass.async_add_executor_job(spa.get_facade, False)
```

## Configuration

NA

## Describe the bug

The custom component generates an error on startup if the Gecko units aren't connected (RF error).  (My tub was temporarily powered down for maintenance.)

Since no other errors have been generated, and things haven't changed, it doesn't look like it is going to poll at some point and recover. I've only waited 15 minutes so far.  

So I'm guessing I'm going to have to restart Home Assistant to get the integration to reconnect.

## Debug log

```text

2021-06-12 11:04:13 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:15 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:17 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:19 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:21 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:23 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:25 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:27 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:29 WARNING (Thread-6) [geckolib.driver.udp_socket] Couldn't find new handler for b'RFERR'
2021-06-12 11:04:39 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 282, in _ping_thread_func
    self.refresh()
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 311, in refresh
    if not self.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
    raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...
2021-06-12 11:04:39 ERROR (MainThread) [custom_components.gecko] Exception during entry setup
Traceback (most recent call last):
  File "/config/custom_components/gecko/__init__.py", line 49, in async_setup_entry
    while not facade.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/automation/facade.py", line 68, in is_connected
    if not self._spa.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
    raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...


```

**Comment by rct** [comment]
@scope666 -    My understanding, based on my own observations, is `RFERR` is an error reported by the Gecko unit connected to the network when doesn't have a radio connection (RF) to the unit in the spa.  For example that's the error that shows up if the spa is temporarily powered down (the spa side unit no longer has power so no RF connection.)

 I wouldn't expect you to have a solid blue light at that point. I saw you mentioned in the other issue that you did.  Perhaps your RF connection is marginal?     (If that's the case repositioning the gecko unit might help.

**Comment by Scope666** [comment]
Yeah, I think something must have introduced new RF interference and it was blocking communications.   I grabbed an ethernet bridge and got the transmitter as close to the tub as possible, this seemed to fix it.

**Comment by rct** [comment]
@Scope666 - Did you have to restart Home Assistant to get it to reconnect with the Gecko units? In my limited experience it seemed the integration never recovered from the RF error. 

> Yeah, I think something must have introduced new RF interference and it was blocking communications. 

Besides distance and things that are in the way, one of the less obvious factors that can affect reception is proximity to other devices that generate RF noise. The noise, (RF interference or RFI), can drown out the other device and prevent it from being heard. For example, Raspberry Pis (especially in plastic cases) are pretty noise, so it's good to keep them away from receivers.

**Comment by Scope666** [comment]
> @Scope666 - Did you have to restart Home Assistant to get it to reconnect with the Gecko units? In my limited experience it seemed the integration never recovered from the RF error.
> 
> > Yeah, I think something must have introduced new RF interference and it was blocking communications.
> 
> Besides distance and things that are in the way, one of the less obvious factors that can affect reception is proximity to other devices that generate RF noise. The noise, (RF interference or RFI), can drown out the other device and prevent it from being heard. For example, Raspberry Pis (especially in plastic cases) are pretty noise, so it's good to keep them away from receivers.

Yes, once I moved the transmitter, I had to restart HA to get the integration working again.  Another thing I noticed, if you set a filter schedule on the tub itself, the temp sensor won't work.  I had to go back in an select one of my profiles in the mobile app to get that to work.

**Comment by gazoodle** [comment]
@Scope666 interesting, that gives me some pointers to work on, TBH I've not handled any tub errors at present but I think it's important for the integration to recover cleanly from faults etc. Well I mean the underlying library actually as we don't do protocol in HA.

**Comment by gazoodle** [comment]
v0.1.0 ought to handle this situation now, please re-open if there are other issues
