### ISSUE TITLE
Exception during entry setup 

### ISSUE THREAD

**Issue by nyxfpv** [gazoodle/gecko-home-assistant#26]
Good Morning all, 
I just installed the integration and I'm running into the following.  can anyone assist me with this

Exception during entry setup 
Traceback (most recent call last):
  File "/config/custom_components/gecko/__init__.py", line 47, in async_setup_entry
    while not facade.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/automation/facade.py", line 68, in is_connected
    if not self._spa.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
    raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...

**Comment by nyxfpv** [comment]
## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.45
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4943
Installed Version | 1.13.2
Stage | running
Available Repositories | 847
Installed Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 18, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 10.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Samba share (9.5.1), Visual Studio Code (3.5.0), AirCast (3.1.1), Terminal & SSH (9.1.3), Mosquitto broker (6.0.1), Node-RED (9.2.0), Home Assistant Google Drive Backup (0.104.3), Zigbee2mqtt (1.18.1-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 1
views | 12
mode | storage

</details>

**Comment by Quellweg22** [comment]
same issue during setup ... logfile:

Logger: homeassistant.util.async_
Source: util/async_.py:132 
First occurred: 18:16:15 (3 occurrences) 
Last logged: 18:32:00

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gecko doing I/O at custom_components/gecko/__init__.py, line 45: facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False)


Logger: custom_components.gecko
Source: util/async_.py:140 
Integration: Gecko (documentation, issues) 
First occurred: 18:16:15 (3 occurrences) 
Last logged: 18:32:00

Exception during entry setup
Traceback (most recent call last):
  File "/config/custom_components/gecko/__init__.py", line 45, in async_setup_entry
    facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False)
  File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 46, in get_facade
    facade = GeckoFacade(GeckoSpa(self).start_connect())
  File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 73, in __init__
    GeckoSpaPack.__init__(self)
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/spapack.py", line 15, in __init__
    GeckoSpaPack.download_if_needed()
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/spapack.py", line 32, in download_if_needed
    GeckoSpaPack.download()
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/spapack.py", line 39, in download
    response = http.request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1264, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/gecko/__init__.py, line 45: facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False)

**Comment by gazoodle** [comment]
v0.0.8 should fix this
