### ISSUE TITLE
1 In Touch-2 work for 2 installed

### ISSUE THREAD

**Issue by dartymath** [gazoodle/gecko-home-assistant#28]
## Configuration

PROXMOX 6.3-2
Home Assistant OS 6.1
Supervisor-2021.06.8
Home Assistant 2021.7.2

GECKO Install with HACS :

Gecko
Version: 0.0.6
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/gazoodle/gecko-home-assistant/issues

Add your logs here.

Logger: geckolib.driver.udp_socket
Source: /usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py:314
First occurred: 11:12:53 (1 occurrences)
Last logged: 11:12:53

Unhandled exception in receive_handler func
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
    receive_handler.handled(self, remote_end)
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 87, in handled
    self._on_handled(self, socket, sender)
  File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 163, in _on_config_received
    raise Exception(
Exception: Cannot find XML configuraton for inYT v65

## Describe the bug

I just purchase a bizone SPA with SPA and SWIM SPA. Each one have a in-touch 2 module.
SPA :  in.ye-5 + K800 + in-touch2
SWIM SPA : in.yt-7 + K800 + in-touch2

both are recognize on the integration UI but only SWIM SPA are connected the other one make an error. same issue if i only connect SPA or after swim spa configutration.

Both work well on the gecko app in IOS or Android

## Debug log

```text

Add your logs here.

2021-07-13 11:12:50 INFO (MainThread) [custom_components.gecko]
-------------------------------------------------------------------
Gecko
Version: 0.0.6
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/gazoodle/gecko-home-assistant/issues
-------------------------------------------------------------------
2021-07-13 11:12:50 INFO (MainThread) [custom_components.gecko] Setup entry for SPA80:1f:12:65:be:b8
2021-07-13 11:12:50 INFO (MainThread) [custom_components.gecko] Locator GeckoLocator(age=0.3874899409711361,has_had_enough_time=False,spas=[Piscine(SPA80:1f:12:65:be:b8)]) ready
2021-07-13 11:12:50 INFO (MainThread) [custom_components.gecko] Setup entry for SPA68:27:19:8e:33:60
2021-07-13 11:12:51 INFO (MainThread) [custom_components.gecko] Locator GeckoLocator(age=0.1089000859647058,has_had_enough_time=False,spas=[Piscine(SPA80:1f:12:65:be:b8), Spa(SPA68:27:19:8e:33:60)]) ready
2021-07-13 11:12:52 INFO (MainThread) [custom_components.gecko] Waiting for facade to be ready
2021-07-13 11:12:52 INFO (MainThread) [custom_components.gecko] Waiting for facade to be ready
2021-07-13 11:12:53 ERROR (Thread-8) [geckolib.driver.udp_socket] Unhandled exception in receive_handler func
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
receive_handler.handled(self, remote_end)
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 87, in handled
self._on_handled(self, socket, sender)
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 163, in _on_config_received
raise Exception(
Exception: Cannot find XML configuraton for inYT v65

**Comment by gazoodle** [comment]
Fixed in v0.0.8
