### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by bopbrev** [gazoodle/gecko-home-assistant#30]
## Version of the custom_component : v0.0.7
Version core-2021.7.4
supervisor-2021.06.8

Getting following fault message
"Failed to set up"
![image](https://user-images.githubusercontent.com/77231851/126914382-3d3aa618-d7e9-4069-a888-33ea0ed76208.png)

log
----------------------------------------------------------
Logger: custom_components.gecko
Source: custom_components/gecko/__init__.py:50
Integration: Gecko (documentation, issues)
First occurred: 11:36:13 PM (1 occurrences)
Last logged: 11:36:13 PM

Exception during entry setup
Traceback (most recent call last):
  File "/config/custom_components/gecko/__init__.py", line 50, in async_setup_entry
    while not facade.is_connected:
  File "/usr/local/lib/python3.9/site-packages/geckolib/automation/facade.py", line 68, in is_connected
    if not self._spa.is_connected:
  File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 319, in is_connected
    raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...
-----------------------------------------------------------------
Detail logs:
-----------------------------------------------------------------
2021-07-25 23:35:43 ERROR (Thread-14) [geckolib.driver.udp_socket] Unhandled exception in receive_handler func
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
receive_handler.handled(self, remote_end)
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 87, in handled
self._on_handled(self, socket, sender)
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 163, in _on_config_received
raise Exception(
Exception: Cannot find XML configuraton for inYT v80
2021-07-25 23:36:12 ERROR (Thread-13) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 295, in _ping_thread_func
self.refresh()
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 324, in refresh
if not self.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 319, in is_connected
raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...
2021-07-25 23:36:13 ERROR (MainThread) [custom_components.gecko] Exception during entry setup
Traceback (most recent call last):
File "/config/custom_components/gecko/__init__.py", line 50, in async_setup_entry
while not facade.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/automation/facade.py", line 68, in is_connected
if not self._spa.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 319, in is_connected
raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...
---------------------------------------------------------------------------

**Comment by nyxfpv** [comment]
yeah, I too have this error.  I believe it's due to new code on the controller.  I hope one day this will be fixed fingers crossed.

**Comment by Johan-Arens** [comment]
I've got the same error with core.2021.8.4, do you guys have any update on that ? I'm running the integration on a KVM VM, on Intel silicon.

**Comment by Johan-Arens** [comment]
I've got the same error with core-2021.8.7.

**Comment by Johan-Arens** [comment]
Guys, I have installed it on a spare VM for testing, if you want me to test something/beta code, just ask. I have just put my spa in service. My in.touch EN version is 70 v14.0, in.touch CO 69 v11.0.

**Comment by manitu1** [comment]
I have the same issue. Pls help someone... Thx.

**Comment by 45Sticks** [comment]
I am also having this issue.  Was there ever a fix?

**Comment by ElbilsChrippe** [comment]
I also have this issue on: in.touch EN version is 88 v15.0, in.touch CO 89 v11.0 inYT 413 v5.0.

Can I help out to debug this somehow, the interface is changed so need to sniff the eth traffic with wireshark or whats the best method to get functions back?

**Comment by ElbilsChrippe** [comment]
Here is a debug log from my setup that I got out.
[home-assistant_gecko_debug.log](https://github.com/gazoodle/gecko-home-assistant/files/7528958/home-assistant_gecko_debug.log)
Seems like there is a problem with the received inYT_C65.xml file. 
Or rather that the inYT v65 is not handled. (searching on)

**Comment by ElbilsChrippe** [comment]
Understand more and more now. Seems like there is a global configuration file here: http://intouch.geckoal.com/gecko/prod/SpaPackStruct.xml
And this file doesnt have the configuration library revision 65, the latest for this page seem to be revision 63.
@gazoodle is there a updates of the SPA configurations from gecko or is that handled by someone else? Is there a way to backtrack the correct configuration and add it to a local xml file instead? Maybe the 63 conf would work with my spa?

E.g. the only diff between 62 and 63 configs are these section added to 63:
`<Exercise>`
`<ExerciseType Type="Enum" Pos="133" Items="NO_EXERCISE|SWIM_EXERCISE" RW="ALL"/>`
`<ExerciseControl Type="Enum" Pos="134" Items="USE_STANDARD_PUMPS" RW="ALL"/>`
`<ExercisePumpsUsed Type="Enum" Pos="135" BitPos="0" MaxItems="8" Items="NO_PUMP|ALL_PUMPS|P2_TO_P5|P3_TO_P5|P4_AND_P5|P5_ONLY||" RW="ALL"/>`
`<ExerciseDedicatedPumps Type="Bool" Pos="135" BitPos="7" RW="ALL"/>`
`<ExerciseNumberOfIntensity Type="Byte" Pos="136" Min="4" Max="10" RW="ALL"/>`
`<ExercisePumpCombination1 Type="Word" Pos="137" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination2 Type="Word" Pos="139" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination3 Type="Word" Pos="141" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination4 Type="Word" Pos="143" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination5 Type="Word" Pos="145" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination6 Type="Word" Pos="147" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination7 Type="Word" Pos="149" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination8 Type="Word" Pos="151" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination9 Type="Word" Pos="153" Min="0" Max="511" RW="ALL"/>`
`<ExercisePumpCombination10 Type="Word" Pos="155" Min="0" Max="511" RW="ALL"/>`
`</Exercise>`

**Comment by ElbilsChrippe** [comment]
Hey guys!

How come my changes locally done doesnt take affect. I've altered the /use/lib/python3.9/site-packages/geckolib/spa.py but the changes dont take affect if I restart HA?!

Is this files stored in .storage somehow or cached somewhere ele?

**Comment by Johan-Arens** [comment]
Hello ElbisChrippe, send me a private email I will give you hints to fix the issue, with xml file. 
yhan26@hotmail.com. 



Johan

**Comment by ElbilsChrippe** [comment]
Yeah I can now confirm it's not the library or integration fault. If you get the message it's because the xml structure doesnt support your spa right yet. I've tried to hardcode the version 63 and it sort of worked actually, but with some limitations in the communication that I cannot connect to lost functionality right now.

I wonder if we can get the xml structure updated some how. Maybe @gazoodle  knows more?

**Comment by Johan-Arens** [comment]
I think so, I’ve got the xml file from him actually.

**Comment by JohnMcLear** [comment]
I'm also experiencing this issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
    receive_handler.handled(self, remote_end)
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 87, in handled
    self._on_handled(self, socket, sender)
  File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 163, in _on_config_received
    raise Exception(
Exception: Cannot find XML configuraton for inYT v65
```

**Comment by gazoodle** [comment]
v0.0.8 should fix this
