### ISSUE TITLE
Any Updates on Error in Setup?

### ISSUE THREAD

**Issue by nmelanson75** [gazoodle/gecko-home-assistant#33]
I am still stuck with the following error and cannot get past the setup.

2021-09-06 22:32:08 ERROR (Thread-69) [geckolib.driver.udp_socket] Unhandled exception in receive_handler func
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
receive_handler.handled(self, remote_end)
File "/usr/local/lib/python3.9/site-packages/geckolib/driver/udp_socket.py", line 87, in handled
self._on_handled(self, socket, sender)
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 163, in _on_config_received
raise Exception(
Exception: Cannot find XML configuraton for inYT v65
2021-09-06 22:32:37 ERROR (Thread-68) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 295, in _ping_thread_func
self.refresh()
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 324, in refresh
if not self.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 319, in is_connected
raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...
2021-09-06 22:32:37 ERROR (MainThread) [custom_components.gecko] Exception during entry setup
Traceback (most recent call last):
File "/config/custom_components/gecko/__init__.py", line 50, in async_setup_entry
while not facade.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/automation/facade.py", line 68, in is_connected
if not self._spa.is_connected:
File "/usr/local/lib/python3.9/site-packages/geckolib/spa.py", line 319, in is_connected
raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...

**Comment by josephus** [comment]
I had the same issue as @nmelanson75 so I did some digging trying to instantiate a GeckoShell directly from a library.

`
DEBUG:geckolib.driver.udp_socket:Sending b'<PACKT><SRCCN>IOS02ac6d28-42d0-41e3-ad22-XXXXXXXX</SRCCN><DESCN>SPA68:27:19:XX:XX:XX</DESCN><DATAS>SFILE\x03</DATAS></PACKT>' to ('192.168.12.226', 10022)
DEBUG:geckolib.driver.udp_socket:Received b'<PACKT><SRCCN>SPA68:27:19:XX:XX:XX</SRCCN><DESCN>IOS02ac6d28-42d0-41e3-ad22-XXXXXX</DESCN><DATAS>FILES,inYT_C65.xml,inYT_S66.xml</DATAS></PACKT>' from ('192.168.12.226', 10022)
DEBUG:geckolib.driver.udp_socket:Received b'FILES,inYT_C65.xml,inYT_S66.xml' from ('192.168.12.226', 10022, b'SPA68:27:19:XX:XX:XX', b'IOS02ac6d28-42d0-41e3-ad22-XXXXXX')
ERROR:geckolib.driver.udp_socket:Unhandled exception in receive_handler func
Traceback (most recent call last):
  File "/home/pi/geckolib/src/geckolib/driver/udp_socket.py", line 312, in dispatch_recevied_data
    receive_handler.handled(self, remote_end)
  File "/home/pi/geckolib/src/geckolib/driver/udp_socket.py", line 87, in handled
    self._on_handled(self, socket, sender)
  File "/home/pi/geckolib/src/geckolib/spa.py", line 173, in _on_config_received
    raise Exception(
Exception: Cannot find XML log for inYT v66
`
Having extracted the latest SpaPackStruct.xml (v24) from the Android app there are definitions for config and log going up to v65, but no v66. Which begs the question: Since the Gecko app is working fine with the above setup maybe we are treating version matching too strict and the android app simply falls back to the highest known version? 

As an alternative one could try dumping the controller firmware, maybe they store the XML files there as well.

**Comment by gazoodle** [comment]
Fixed in v0.0.8
