### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by stepir** [gazoodle/gecko-home-assistant#36]
Hi

I'm running Home Assistant 2021.9.6 with custom component V0.0.7

My logs are full of the following:

```
2021-11-11 17:13:06 ERROR (Thread-6) [geckolib.driver.accessor] Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/accessor.py", line 124, in _get_value
    data = self.items[data]
IndexError: list index out of range
2021-11-11 17:13:06 ERROR (Thread-6) [geckolib.driver.accessor] Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/accessor.py", line 124, in _get_value
    data = self.items[data]
IndexError: list index out of range
2021-11-11 17:13:21 ERROR (Thread-6) [geckolib.driver.accessor] Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/accessor.py", line 124, in _get_value
    data = self.items[data]
IndexError: list index out of range
2021-11-11 17:13:21 ERROR (Thread-6) [geckolib.driver.accessor] Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/accessor.py", line 124, in _get_value
    data = self.items[data]
IndexError: list index out of range
```

although everything seems to be working fine - is the above normal? are others seeing the same? is there a way to solve the index out of range error?

TIA

**Comment by gazoodle** [comment]
Hmm, not seen this one, but I wonder if you've got a fault on your tub that is causing this.

Do you get any info on the mobile app? Also what Gecko pack and version are you using, so I can take a look at the config?

**Comment by stepir** [comment]
> Hmm, not seen this one, but I wonder if you've got a fault on your tub that is causing this.
> 
> Do you get any info on the mobile app? Also what Gecko pack and version are you using, so I can take a look at the config?

hi @gazoodle 

no the app won't report any fault and from what I can tell everything run fine (including your integration despite the errors above).

I have a gecko in.touch 2 https://geckointouch.com/concept#sparemotecontrol

![IMG_B2E94A72CA44-1](https://user-images.githubusercontent.com/36472935/152741346-0310b711-4157-4f57-a608-3ef810c0ea5e.jpeg)

**Comment by gazoodle** [comment]
Does this still occur with v0.1.0?

**Comment by stepir** [comment]
looks good now! thanks @gazoodle

**Comment by stepir** [comment]
still there:

2022-03-22 20:11:37 ERROR (MainThread) [geckolib.driver.accessor] Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']. Value is 5
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/geckolib/driver/accessor.py", line 103, in _get_value
    data = self.items[data]
IndexError: list index out of range

**Comment by gazoodle** [comment]
OK, so we have an odd situation here. The pack info shows that there are 5 possible values for the (zero based) enum for `inFloErrorType` yet the pack is returning 5 which is one past the end of the possible enum values - hence the complaint.

Since we don't actively use that accessor in any code, we can ignore the error as it doesn't affect any functionality, but I'm intrigued and would like to understand more. There is another user who has the same issue, as linked above and a search of the internet has shown that there are others who also get this, so I'll reopen this issue to see if we can understand more about it.

The fact that this pack node is the same in all inYJ and inYT pack declarations, and at the same position (374) leads me to think that it is a pretty stable feature in the tub, it also isn't adjacent to any bit position fields that I might be misunderstanding how to interpret (like needing some bitmask).

Also, you initially said it was OK, only then to report that it was happening again which leads me to think that this is intermittent fault, sometimes I suspect it will be 0 - FLOW_OK, which is what my in inYT returns, other times it is 5 whatever that means.

Maybe more information will turn up when I implement the error reporting part that is on my plan, perhaps there are other correlations we can make.

**Comment by stepir** [comment]
yes it was not showing since a while - and can confirm apart from the log nothing seems to be misworking

**Comment by maegibbons** [comment]
Hi.

This has been happening on our tub since inception of using the integration.  Back in the spastruct days,  I just edited the xml and added "UNKOWN" to the list.  It's obviously something that the controller spews out occasionally.

I would suggest you do the same in current code.  I.e. allow the 5 index and map it to "UNKNOWN" to avoid the logging.

**Comment by gazoodle** [comment]
> Hi.
> 
> This has been happening on our tub since inception of using the integration. Back in the spastruct days, I just edited the xml and added "UNKOWN" to the list. It's obviously something that the controller spews out occasionally.
> 
> I would suggest you do the same in current code. I.e. allow the 5 index and map it to "UNKNOWN" to avoid the logging.

@maegibbons  why didn't I think of that!!! Thanks, I'll make a generic fix and also dump myself a debug message

**Comment by gazoodle** [comment]
v0.1.8 ought to resolve this issue.
