### ISSUE TITLE
Setup errors

### ISSUE THREAD

**Issue by Philzy10** [gazoodle/gecko-home-assistant#54]
First of all this is a pretty great integration, thank you very much Gazoodle!  I am seeing my spa in Home Assistant and can control the heater, blower and lights!  My issue is I have no control over the jet pumps and am posting my error logs in hopes of someone being able to help.  My particular spa is a Hydropool Spa with 2 jet pumps.  Pump #1 has 2 settings, hi and low we'll call them, and pump #2 is either on or off.  I'm not very savvy when it comes to Home Assistant but I can follow directions and tutorials fairly well, any help is greatly appreciated!!  Thanks!!

2022-04-15 11:15:29 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gecko which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-15 11:15:32 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2022-04-15 11:16:03 ERROR (MainThread) [homeassistant.setup] Setup failed for button: Integration not found.
2022-04-15 11:16:03 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My Spa for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 209, in async_setup_entry
return await hass.data[DOMAIN].async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
platform = await async_prepare_setup_platform(
File "/usr/src/homeassistant/homeassistant/setup.py", line 328, in async_prepare_setup_platform
platform = integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 779, in exec_module
File "<frozen importlib._bootstrap_external>", line 916, in get_code
File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/custom_components/gecko/fan.py", line 1
Fan platform for Gecko.
^
SyntaxError: invalid syntax
2022-04-15 11:16:03 WARNING (MainThread) [geckolib.driver.protocol.unhandled] No handler for b'RMREQ\x01\x00\x00\x01\x02\x1e\x00\x01\x03<\x00\x01\x04b\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' from ('192.168.32.68', 10022, b'SPA80:1f:12:65:f3:28', b'IOS7aca5272-9d53-4c96-b43d-df43cc457e34') found, message ignored

**Comment by gazoodle** [comment]
Lets get some diags.

Open a command prompt/terminal session
```
$ pip install geckolib
 :
$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>from geckolib import GeckoShell
>>>GeckoShell.run()
 :
Connecting to spa `Spa` at 10.x.x.x ... connected!
Heater: Temperature 39.5°C, SetPoint 39.5°C, Real SetPoint 39.5°C, Operation Idle
Pump 1: OFF
Waterfall: OFF
Pump 2: OFF
Lights: OFF
WaterCare: Waiting...
Smart Winter Mode:Risk: NO
Circulating Pump: OFF
Ozone: OFF
Smart Winter Mode:Active: False
Filter Status:Clean: False
Filter Status:Purge: False
Economy Mode: False
Spa$ 
```
You should be connected to your spa now, so take a snapshot now

```
spa$ snapshot After connection
```

Turn on one of your pumps either from the spa panel, or the Gecko app

```
spa$ refresh
spa$ snapshot Pump on
spa$ exit
```

Then find the file `client.log` and email it to `gazoodle at hash dot fyi`

Thanks.

**Comment by Philzy10** [comment]
Hi, thanks so much for your reply!  This is about as far as I get.  I neglected to mention that I’m running Home Assistant in a Docker container on a Synology DS916+ NAS, not sure if that changes things but after SSHing into my NAS and trying your first command I get the command not found error. Again, sorry, I’m not very knowledgeable with this stuff so I’m at a loss when I run into problems such as this. Your help is very much appreciated, thank you!

Mike

**Comment by Philzy10** [comment]
Hi again, I did some researching and figured out how to do what you wanted me to.  I followed all the steps you asked me to and everything seems to have worked as it should have. My only issue now is finding and retrieving the darn client.log file.  I can’t, for the life of me, find it.  Any help in finding it and copying it to a location where I can view it and get it to you would be awesome, again, thank you very much!

Mike

**Comment by gazoodle** [comment]
Well done @Philzy10, kudos! I think I missed a command for you in my script which is probably why you don’t have a log file, I’m so sorry.

`>>> GeckoShell.run(‘log file client.log’)`

the log file will (or should) be in the folder you started the python session from.

**Comment by Philzy10** [comment]
Thanks Gazoodle!  I still can’t seem to get it to work properly. I tried doing it again the original way and can’t find the client.log file, not sure what I’m doing wrong, anyway, here’s a screenshot of what I’ve tried to do with your new command and I get a SyntaxError.....hope this helps, thanks again!



Sent from Mail for Windows

**Comment by Philzy10** [comment]
Sorry, I meant to send this screenshot with the last one, just showing that I am able to connect to my spa.



Sent from Mail for Windows

**Comment by gazoodle** [comment]
I should have dug up a previous example instead of trying to recall it off the top of my head …

```python
from geckolib import GeckoShell
GeckoShell.run(["logfile client.log"])
 :
 :
```

**Comment by gazoodle** [comment]
I think this is resolved now.
