### ISSUE TITLE
Exception is thrown and fails to connect to Mr. Steam gecko controller.

### ISSUE THREAD

**Issue by toxikman** [gazoodle/gecko-home-assistant#99]
## Version of the custom_component
Geck integration: Version 0.1.9
Home assistant: Version 2024.2.5

## Describe the bug
1) While trying to connect to a Mr. Steam gecko controller, it times out (see screenshot).
2) A python exception is output to the HA log.

<img width="419" alt="Screenshot 2024-03-09 at 12 55 13 PM" src="https://github.com/gazoodle/gecko-home-assistant/assets/997018/a3f3e2d4-e079-4526-a9ab-b344afb2f53e">

## Debug log

```2024-03-09 12:48:44.015 ERROR (MainThread) [geckolib.async_spa] Exception during spa connection
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 354, in _connect
self.accessors[GeckoConstants.KEY_PACK_CONFIG_ID].value,
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PackConfID'
2024-03-09 12:49:36.012 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
await self.async_connect(self._spa_identifier, self._spa_address)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
return await self.async_connect_to_spa(spa_descriptors[0])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
await self._spa.connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 354, in _connect
self.accessors[GeckoConstants.KEY_PACK_CONFIG_ID].value,
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PackConfID'
```

**Comment by fwuehr** [comment]
I am facing the same issue since I upgraded home assistant to the latest version. Seems to be a general issue with the newer HA versions 😕 @gazoodle can you confirm this ?

**Comment by fwuehr** [comment]
Issue seems to be resolved after update to 2024.3.3

**Comment by dannyb2100** [comment]
I have been having this issue and cannot see why.
If you're still having this error.

Here's a simple way to auto-restart the service, after it gets into a failure loop.
(It doesn't solve the issue of it failing, but does keep the spa connected)
```YAML
alias: Restart Integration on Error
description: Automatically restarts an integration when a specific error occurs.
trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      logger: "geckolib.async_spa"
      level: "ERROR"
      message: Cannot set value, protocol retry count exceeded
action:
  - service: button.press
    target:
      entity_id: button.spaname_reconnect
    data: {}
```

Just replace the entity_id with yours.

**Comment by toxikman** [comment]
Still not working with the latest Home Assistant 2024.4.4:
```
Error setting up entry My Steamer for gecko
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gecko/__init__.py", line 85, in async_setup_entry
    if not await spaman.wait_for_facade():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 360, in wait_for_facade
    await asyncio.sleep(GeckoConstants.ASYNCIO_SLEEP_TIMEOUT_FOR_YIELD)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

```
Exception during spa connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
    await self._connect()
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 354, in _connect
    self.accessors[GeckoConstants.KEY_PACK_CONFIG_ID].value,
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PackConfID'
```

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
    await self.async_connect(self._spa_identifier, self._spa_address)
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
    return await self.async_connect_to_spa(spa_descriptors[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
    await self._spa.connect()
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
    await self._connect()
  File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 354, in _connect
    self.accessors[GeckoConstants.KEY_PACK_CONFIG_ID].value,
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PackConfID'
```

**Comment by toxikman** [comment]
Still not working with HA 2024.7.2. Hangs forever after selecting "My Steamer" in the setup dialog, then getting slightly different WARNINGS in the HA log:

```
2024-07-17 12:11:42.075 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('geckolib.driver.packs.mrsteam',) in /usr/local/lib/python3.12/site-packages/geckolib/async_spa.py, line 270: GeckoPack = importlib.import_module(pack_module_name).GeckoPack inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
await self.async_connect(self._spa_identifier, self._spa_address)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
return await self.async_connect_to_spa(spa_descriptors[0])
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
await self._spa.connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 270, in _connect
GeckoPack = importlib.import_module(pack_module_name).GeckoPack
2024-07-17 12:11:42.082 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('geckolib.driver.packs.mrsteam-cfg-3',) in /usr/local/lib/python3.12/site-packages/geckolib/async_spa.py, line 289: GeckoConfigStruct = importlib.import_module( inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
await self.async_connect(self._spa_identifier, self._spa_address)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
return await self.async_connect_to_spa(spa_descriptors[0])
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
await self._spa.connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 289, in _connect
GeckoConfigStruct = importlib.import_module(
2024-07-17 12:11:42.086 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('geckolib.driver.packs.mrsteam-log-3',) in /usr/local/lib/python3.12/site-packages/geckolib/async_spa.py, line 309: GeckoLogStruct = importlib.import_module(log_module_name).GeckoLogStruct inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump
await self.async_connect(self._spa_identifier, self._spa_address)
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect
return await self.async_connect_to_spa(spa_descriptors[0])
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa
await self._spa.connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 309, in _connect
GeckoLogStruct = importlib.import_module(log_module_name).GeckoLogStruct
2024-07-17 12:11:45.927 ERROR (MainThread) [geckolib.async_spa] Exception during spa connection
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect
await self._connect()
File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 354, in _connect
self.accessors[GeckoConstants.KEY_PACK_CONFIG_ID].value,
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PackConfID'
```

**Comment by toxikman** [comment]
OK so it loads now and let's me assign the device to an area, but I'm not seeing any entities that would let me turn it on and off, set the current target temperature, or set a timer to run the steam. I only see diagnostic entities:

![Image](https://github.com/user-attachments/assets/53ce5665-e064-4130-aa63-d4f29f504bd7)

Here's what's in the log file:

```
2025-02-18 13:46:24.514 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My Steamer for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 96, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 186, in async_setup_entry
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Config entry My Steamer (01JMDGDJANETEFSZ9CF2394FHR) for gecko.sensor has already been setup!
2025-02-18 13:46:24.529 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My Steamer for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 68, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 186, in async_setup_entry
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Config entry My Steamer (01JMDGDJANETEFSZ9CF2394FHR) for gecko.button has already been setup!
2025-02-18 13:46:28.494 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry My Steamer for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 101, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2025-02-18 13:46:28.500 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry My Steamer for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 73, in async_unload_entry
    return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2025-02-18 13:46:28.512 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My Steamer for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 96, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 186, in async_setup_entry
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Config entry My Steamer (01JMDGDJANETEFSZ9CF2394FHR) for gecko.sensor has already been setup!
2025-02-18 13:46:28.516 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My Steamer for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 68, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 186, in async_setup_entry
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Config entry My Steamer (01JMDGDJANETEFSZ9CF2394FHR) for gecko.button has already been setup!
2025-02-18 13:46:51.071 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'gecko' sets option flow config_entry explicitly, which is deprecated at custom_components/gecko/config_flow.py, line 170: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/gazoodle/gecko-home-assistant/issues
2025-02-18 13:47:32.567 ERROR (MainThread) [geckolib.async_spa] Cannot get watercare, protocol retry count exceeded
2025-02-18 13:48:47.293 ERROR (MainThread) [geckolib.async_spa] Cannot get watercare, protocol retry count exceeded
2025-02-18 13:50:06.903 ERROR (MainThread) [geckolib.async_spa] Cannot get watercare, protocol retry count exceeded
```

**Comment by gazoodle** [comment]
Ahh, that’s not so bad. I’ll look through those traces and hopefully we can get the snapshot button loaded. It was never going to have any MrSteam controls in because I don’t have any data on what to look for. After we get an integration loaded and stable, we can gather data and go from there if you’re ok to help?

**Comment by toxikman** [comment]
For sure, I'm happy to help however I can. I'm a dev so I can do various technical and coding stuff, I just don't have any experience developing for Hass other than YAML, but I can learn.

**Comment by ChrisRut** [comment]
I am in the same boat, I can't see how to get the snapshot button loaded from the device page:

<img width="1296" alt="Image" src="https://github.com/user-attachments/assets/2782ac98-0047-4388-bac5-cca69b9ade4d" />

I've enabled debug logs and attached them here: 

[home-assistant_2025-02-22T20-11-20.689Z.log](https://github.com/user-attachments/files/18925306/home-assistant_2025-02-22T20-11-20.689Z.log)

**Comment by ChrisRut** [comment]
Confirmed I can see the sensors now:

<img width="655" alt="Image" src="https://github.com/user-attachments/assets/e73e0296-c3e8-459a-bb2c-aeb7cbff05a8" />

**Comment by gazoodle** [comment]
Closing this issue now that basic support is implemented. Any issues with Mr.Steam units, please open new separate issues. Thanks to everyone who helped to get this functioning.

**Comment by toxikman** [comment]
Thank you guys so much for your time! It works!!
